language: node_js
node_js:
  - '10'

os:
  - linux
  - osx

script:
  - npm run lint
  - npm run test:browser -- --testTimeout=120000 --forceExit
  - npm run test:cover -- --testTimeout=120000 --forceExit
  - npm run build
  - npm run docs

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Deploy documentation to Github Pages (only on Linux)
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux

  # Do a semantic release (only on Linux)
  - provider: script
    skip_cleanup: true
    script: npx semantic-release --branch $TRAVIS_BRANCH
    on:
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_BRANCH =~ ^(master|next)$

