#!/bin/sh

# A little script to make it a litle easier (and in a manner more
# similar to end use) to use the CLI during development of this repo.
# For example instead of,
#   npm run cli:dev -- command --option1 --option2=value
# you can use,
#   ./executa command --option1 --option2=value

# Change into the current directory of this script so that
# it can be run from anywhere
cd "$(dirname "$0")"

# Run the NPM script
npm run cli:dev -- "$@"
